// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// settings
export const GET_SETTINGS = 'GET_SETTINGS'
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS'
export const GET_SETTINGS_FAILED = 'GET_SETTINGS_FAILED'

// product categories
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES'
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS'
export const GET_PRODUCT_CATEGORIES_FAILED = 'GET_PRODUCT_CATEGORIES_FAILED'

// food categories
export const GET_FOOD_CATEGORIES = 'GET_FOOD_CATEGORIES'
export const GET_FOOD_CATEGORIES_SUCCESS = 'GET_FOOD_CATEGORIES_SUCCESS'
export const GET_FOOD_CATEGORIES_FAILED = 'GET_FOOD_CATEGORIES_FAILED'

// map location
export const GET_MAP = 'GET_MAP'
export const GET_MAP_SUCCESS = 'GET_MAP_SUCCESS'
export const GET_MAP_FAILED = 'GET_MAP_FAILED'

export const SET_MAP = 'SET_MAP'
export const SET_MAP_SUCCESS = 'SET_MAP_SUCCESS'
export const SET_MAP_FAILED = 'SET_MAP_FAILED'
